FROM ubuntu:16.04

WORKDIR /tmp/test
COPY . /tmp/test

#RUN bash common_setup.sh
#RUN bash dev_setup.sh

#RUN bash langs/clang_setup.sh
#RUN bash langs/gcc_setup.sh
#RUN bash langs/go_setup.sh
#RUN bash langs/java_setup.sh
#RUN bash langs/proto_setup.sh
RUN bash langs/python_setup.sh

#RUN bash libs/boost_setup.sh
#RUN bash libs/llvm_setup.sh
#RUN bash libs/opencv_setup.sh
#RUN bash libs/opengl_setup.sh
#RUN bash libs/swig_setup.sh

#RUN bash tools/bazel_setup.sh
#RUN bash tools/cmake_setup.sh
#RUN bash tools/docker_setup.sh
#RUN bash tools/mkube_setup.sh
#RUN bash tools/nvm_setup.sh
RUN bash tools/pyenv_setup.sh
#RUN bash tools/glide_setup.sh

#RUN bash tools/buildtools/grunt_setup.sh
#RUN bash tools/buildtools/ngyp_setup.sh

#RUN bash tests/prep.sh
#RUN python configs/configure.py tests/fake.yaml
