FROM ubuntu:16.04

ENV WDIR /tmp/test
WORKDIR $WDIR

COPY utils $WDIR/utils

COPY common_setup.sh $WDIR
RUN bash common_setup.sh
COPY dev_setup.sh $WDIR
RUN bash dev_setup.sh

COPY tests $WDIR/tests
RUN bash tests/prep.sh
COPY configs $WDIR/configs
RUN python configs/configure.py tests/fake.yaml

#CMD [ "python", "tests/verify.py" ]
