FROM ubuntu:14.04

COPY ./ubuntu /tmp
WORKDIR /tmp

RUN bash ubuntu/app_setup.sh

# development setup
RUN bash ubuntu/tools/docker_setup.sh
RUN bash ubuntu/tools/mkube_setup.sh
RUN bash ubuntu/tools/nvm_setup.sh

RUN bash ubuntu/langs/go_setup.sh

RUN bash cfg/cfg_setup.sh
