# mkaichen/bionic_conan_cmake
FROM ubuntu:18.04

# install preliminary deps
RUN apt-get update &&\
    apt-get install -y wget python3 python3-pip python3-setuptools git libssl-dev &&\
    pip3 install wheel

# install cmake
RUN apt purge --auto-remove cmake &&\
    cd /tmp &&\
    wget https://cmake.org/files/v3.19/cmake-3.19.1.tar.gz &&\
    tar -xzvf cmake-3.19.1.tar.gz &&\
    cd cmake-3.19.1/ &&\
    ./bootstrap &&\
    make &&\
    make install

# install conan
RUN pip3 install conan
