FROM ubuntu:18.04

RUN mkdir -p /tmp/setup/tools
RUN mkdir -p /tmp/setup/langs
COPY ../tools/bazel_setup.sh /tmp/setup/tools
COPY ./python_setup.sh /tmp/setup/langs
COPY ../utils /tmp/setup/utils

RUN bash /tmp/setup/tools/bazel_setup.sh
RUN bash /tmp/setup/langs/python_setup.sh
